# Generated by Django 3.2.3 on 2021-05-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210524_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalFinishedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('github_url', models.URLField(blank=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.developmentstack')),
            ],
        ),
    ]
