# Generated by Django 3.2.3 on 2021-05-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_personalfinishedproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('my_level_support', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=0, max_length=1)),
            ],
        ),
    ]
