# Generated by Django 3.2.3 on 2021-06-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_personalproject_importance_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalFinishedProject',
        ),
    ]
