# Generated by Django 3.2.3 on 2021-06-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_delete_personalfinishedproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalproject',
            name='project_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private'), ('forked', 'forked')], default='public', max_length=25),
        ),
    ]
