# Generated by Django 3.2.3 on 2021-06-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_personalproject_project_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalproject',
            old_name='project_type',
            new_name='project_visibility',
        ),
    ]
