# Generated by Django 3.2.3 on 2021-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_personalproject_future_development_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalproject',
            name='future_development_notes',
            field=models.TextField(default='None'),
        ),
    ]
