# Generated by Django 3.2.3 on 2021-06-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_organizations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizations',
            new_name='Organization',
        ),
    ]
