# Generated by Django 3.2.3 on 2021-06-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_rename_organizations_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentReadingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
