# Generated by Django 3.2.3 on 2021-06-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210622_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversityClasses',
        ),
        migrations.DeleteModel(
            name='UniversityProject',
        ),
    ]
