# Generated by Django 3.2.3 on 2021-06-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210628_2239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='PortfolioProject',
        ),
    ]
