# Generated by Django 3.2.3 on 2021-06-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_delete_currentreadingbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
