# Generated by Django 3.2.3 on 2021-07-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_delete_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalproject',
            name='future_development_notes',
        ),
    ]
