# Generated by Django 3.2.3 on 2021-06-29 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_delete_organization'),
        ('learning', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='stack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.developmentstack'),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
