# Generated by Django 3.2.3 on 2021-06-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20210629_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='None'),
        ),
    ]
