# Generated by Django 3.2.3 on 2021-06-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='source_platform',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
