# Generated by Django 3.2.3 on 2021-06-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_course_source_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
